[feature] be able to get file location of fs events
heimdalljs/heimdall-fs-monitor pull request #27
Opened 2020-04-23 01:09 UTC by gabrielcsapo

# Motivation

I am working on a tool to debug broccoli performance here https://github.com/gabrielcsapo/broccoli-inspector. Getting the fs stats is incredibly useful to know what percentage of the time is spent in IO. Debugging where that IO activity very difficult. Most fs related functionality might be abstracted away or hard to track down. This should allow us to level up to developers where fs related time is spent and where.

2020-04-24 19:47 UTC, gabrielcsapo commented on index.js
> +                  const e = new Error();
we should turn this off by default.

2020-04-24 19:48 UTC, gabrielcsapo commented on index.js
> +                  const e = new Error();
We should use a library for this that is tested.

2020-04-24 19:49 UTC, gabrielcsapo commented on index.js
> +                  const e = new Error();
https://github.com/sindresorhus/caller-callsite

2020-04-24 19:50 UTC, stefanpenner requested changes

2020-04-24 19:50 UTC, stefanpenner commented on index.js
> +                try {
let's use an existing library for this

2020-04-24 19:50 UTC, stefanpenner commented on index.js
> +                try {
this should likely be opt-in, due to historical performance issues with `Error.stack` that being said, it may be worth checking if that cost is still prohibitively high (it may have improved more...).

2020-04-25 01:31 UTC, gabrielcsapo commented on index.js
> +                try {
I ran a couple of tests on jsbench. Here is one that proves that browser performance for creating errors is extremely expensive https://jsbench.me. I also ran a benchmark locally;

```
const Benchmark = require('benchmark');

var suite = new Benchmark.Suite;

// add tests
suite
.add('Overhead#WithError', function() {
  new Error();
})
.add('Overhead#WithoutError', function() {
  // noop
})
.on('cycle', function(event) {
  console.log(String(event.target));
})
.on('complete', function() {
  console.log('Fastest is ' + this.filter('fastest').map('name'));
})
.run({ 'async': true });
```

and the outputs are 

```
Overhead#WithError x 250,835 ops/sec ±2.19% (77 runs sampled)
Overhead#WithoutError x 792,984,189 ops/sec ±0.78% (90 runs sampled)
Fastest is Overhead#WithoutError
```

I think making this an opt-in makes the most sense.

2020-04-25 01:33 UTC, gabrielcsapo commented
@stefanpenner I used the modules we talked about offline and the issue is that they require node@8. If @lynchbomb is okay with major bumping we can add it.

2020-04-27 15:10 UTC, stefanpenner commented on index.js
> +                try {
Ya looks no better than how I remembered it.

@gabrielcsapo thanks for the updated info!

2020-04-29 19:48 UTC, gabrielcsapo commented
@lynchbomb @stefanpenner I bumped all dependencies, bump to 1.0.0 and added a changelog showing the changes.

2020-05-04 20:21 UTC, stefanpenner requested changes

2020-05-04 20:21 UTC, stefanpenner commented on index.js
> +                if(monitor.captureTracing) {
lets use an env var here instead, will make turn it on/off at runtime easier, and it will also make it easier to turn on/off for any given process at startup.

2020-05-04 20:21 UTC, stefanpenner commented on index.js
> +                      statckTrace: cleanStack(extractStack(error), { pretty: true }),
typoe `statckTrace` -> `stackTrace`

2020-05-04 20:23 UTC, stefanpenner requested changes

2020-05-04 20:23 UTC, stefanpenner commented on index.js
> +      this.invocations.push(location)
this.invocations will grow forever, this makes sense as it is a debugging tool. 

* Hopefully this is also opt-in.
* we should be sure to add a doc snippet with the env var describing it's downsides. Performance regression, and memory leak/pressure etc.

2020-05-04 20:27 UTC, stefanpenner requested changes

2020-05-04 20:27 UTC, stefanpenner commented on index.js
> +      this.invocations.push(location)
I believe, there are always a finite number of unique callstacks. At-least in typically use-cases. Given that, there may be an efficient trick, to not store every invocations callstack.

In theory, an interned string will auto-dedupe. I doubt the string that comes out of the stack, or the cleaned stack will be interned by default. But it may be worth exploring, it may be an intern, or maybe forcing it to be interned is viable.

2020-05-04 20:34 UTC, gabrielcsapo commented on index.js
> +      this.invocations.push(location)
Look into making this a hash map so that we aren't pushing the same stack multiple times

condense the information to show how many times a stack was invoked.

2020-05-12 21:14 UTC, stefanpenner requested changes

2020-05-12 21:14 UTC, stefanpenner commented on index.js
> +                if(monitor.captureTracing) {
If this check is against the actual env var, it could be toggled at runtime. Given that your broccoli-inspector may want to toggle this at runtime, should we make this change?

2020-05-12 23:19 UTC, gabrielcsapo commented on index.js
> +                if(monitor.captureTracing) {
I made this a getter as we talked about offline!

2020-05-12 23:43 UTC, stefanpenner commented on index.js
> +                  } catch(ex) {}
one last nit, if something goes wrong we may want to `debug` log

2020-05-13 00:02 UTC, gabrielcsapo commented on index.js
> +                  } catch(ex) {}
added the debug for this

2020-06-10 17:08 UTC, gabrielcsapo commented
@stefanpenner thoughts on this?

2020-06-11 21:59 UTC, stefanpenner requested changes

2020-06-11 21:59 UTC, stefanpenner commented on tests.js
> +    process.env.HEIMDALL_FS_MONITOR_CALL_TRACING = 1;
A corresponding afterEach to restore this env var seems to be missing. We should avoid leaving dirty global state in tests

2020-06-13 02:11 UTC, gabrielcsapo commented
@stefanpenner I moved the reset logic to a beforeEach.

2020-06-23 18:03 UTC, stefanpenner approved these changes

2020-06-23 18:03 UTC, stefanpenner commented
LGTM thanks :)

2020-06-23 18:16 UTC, merged

2020-06-23 18:18 UTC, stefanpenner commented
released as v1.1.0 🎉