Guard against double registerMonitor calls
heimdalljs/heimdall-fs-monitor pull request #7
Opened 2016-11-16 00:47 UTC by zackthehuman

Since it is possible that the fs-monitor could be included multiple times in a project through different dependencies, we need to guard against double registering via `registerMonitor`. This has the downside of making `statsFor` not return anything when we didn't register. In order to fix that, we make instances of `FSMonitor` essentially no-op since the alternative would result in double counting `fs` operations.

We control this via a shared `isEnabled` variable which acts kind of like a semaphore.

2016-11-16 04:50 UTC, hjdivad requested changes

2016-11-16 04:50 UTC, hjdivad commented on index.js
> +// heimdall session. In that case, we need to guard against double-couting by
this is probably how i would spell counting, but i think most people would recognize it as a typo

2016-11-16 04:50 UTC, hjdivad commented on index.js
> +var m;
can we just get rid of `m`?  nobody seems to use it

2016-11-16 04:50 UTC, hjdivad commented on index.js
> +  isEnabled = false;
wait how could this possibly work?  other instances will have other modules in memory and other `isEnabled` flags;  the shared state is not in this module, it's on the heimdall session.

The logic I had tried to describe for `isEnabled` is
```js
var isEnabled = false;
if (! heimdall.hasMonitor('fs')) {
  // we may have multiple versions of heimdall-fs-monitor due to dependencies, but we only want one of them to actually be active per heimdall session
  heimdall.registerMonitor('fs', function FSSchema() {});
  isEnabled = true;
}
```

2016-11-16 04:50 UTC, hjdivad commented on index.js
> +  if (this._isEnabled) {
this seems like a reasonable place for us to warn with `heimdalljs-logger` no?

In the case that you ran into we would never `start` the second FSMonitor instance.  If someone calls `start` on one that `isEnabled === false` that seems like something we should warn about, no?  what do you think?

2016-11-16 04:52 UTC, hjdivad commented
@zackthehuman awesome thanks; have a couple of changes

2016-11-16 19:37 UTC, zackthehuman commented on index.js
> +  isEnabled = false;
There are two issues at play.

1. Shared state from the heimdall session for which we want to prevent double-registers
2. Shared state in the fs-monitor module itself (due to `npm link`?)

If we don't prevent against multiple `FSMonitors` for the same heimdall session, then we'll get double counting.

Without this guard in place, this is what happens to me:

```
Cannot read property '0' of undefined
TypeError: Cannot read property '0' of undefined
    at Metric.stop (/home/zmulgrew/workspace/heimdall-fs-monitor/index.js:66:40)
    at FSMonitor._measure (/home/zmulgrew/workspace/heimdall-fs-monitor/index.js:91:7)
    at Object.realpathSync (/home/zmulgrew/workspace/heimdall-fs-monitor/index.js:110:30)
    at toRealPath (module.js:112:13)
    at tryFile (module.js:108:22)
    at tryPackage (module.js:96:10)
    at Function.Module._findPath (module.js:154:20)
    at Function.Module._resolveFilename (module.js:324:25)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
```

2016-11-17 06:16 UTC, zackthehuman commented on index.js
> +  if (this._isEnabled) {
Agreed. Will add logging in the morning.

2016-11-17 06:17 UTC, zackthehuman commented
@hjdivad Updated. Used two flags (one for "I registered the monitor" and another for "I'm the first instance").

2016-11-17 16:11 UTC, hjdivad requested changes
Looks great!

Two things
- [ ] very minor comment improvement
- [ ] log warn if calling `start()` when `!_isEnabled`

2016-11-17 16:11 UTC, hjdivad commented on index.js
> +  // session to be inert.
Comment is wrong; `isFirstInstance` refers to whether or not this is the first instance of this module; `isMonitorRegistrant` refers to whether or not some other fs monitor is registered with the session.

Maybe
```js
// Flip this to false because we want other instances from the same module to be inert.
```

2016-11-17 16:12 UTC, hjdivad commented
@zackthehuman obviously if you want to add tests too that would be great, but in any case once this lands i'll have to test manually before releasing

2016-11-17 18:00 UTC, zackthehuman commented
@hjdivad I don't really have cycles to set up the test suite right now. I have been testing this locally since this issue is currently blocking me and these changes effectively unblock me, assuming we bump all the things to include this new version.

I am also not sure how we could actually test one of the scenarios in an automated way where two non-flattened fs-monitors share the same heimdall session.

2016-11-17 18:03 UTC, hjdivad approved these changes

2016-11-17 18:03 UTC, merged

2016-11-17 18:04 UTC, hjdivad commented
@zackthehuman no worries; i need to test manually before cutting a release anyway